#!/bin/bash -eu

if [ $# -ne 1 ]; then
  echo "Usage: ./deploy VERSION_MANIFEST_JSON_STRING"
  exit 1
fi

test_rp_msa_version=$(jq -r '.ida_msa_version' <<< "$1")
if [[ "$test_rp_msa_version" == "null" ]]; then
  echo "No ida_msa_version entry in ${1}"
  exit 1
fi

/usr/bin/apt-get -qq update

for PACKAGE in test-rp-msa; do
  VERSION_VAR=${PACKAGE//-/_}_version
  VERSION_SPECIFIED=${!VERSION_VAR}

  /usr/bin/apt-get install \
    -qfy --reinstall --force-yes \
    -o DPkg::Options::=--force-confnew \
    $PACKAGE="$VERSION_SPECIFIED"
done
