dist: trusty
language: java

env:
  global:
    - VERIFY_USE_PUBLIC_BINARIES=true

jdk:
  - oraclejdk8
  - openjdk8
  - openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
